server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: looktech-plutus
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:plutus}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Redis Configuration
  redis:
    # 集群模式配置
    cluster:
      enabled: ${REDIS_CLUSTER_ENABLED:false}
      nodes: ${REDIS_CLUSTER_NODES:ai-agent-cidor4.serverless.use1.cache.amazonaws.com:6379}
    # 单节点模式配置（本地开发环境）
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    timeout: ${REDIS_TIMEOUT:10000}
    # 通用配置
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
  
  # Disable Redis repositories
  data:
    redis:
      repositories:
        enabled: false

# Custom Configuration
credit:
  reservation:
    ttl-seconds: ${CREDIT_RESERVATION_TTL:3600}  # 1 hour
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    window-seconds: ${RATE_LIMIT_WINDOW:60}
    max-requests: ${RATE_LIMIT_MAX_REQUESTS:100}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.looktech.plutus.controller
  paths-to-match: /api/** 
# Logging Configuration
logging:
  level:
    root: INFO
    com.looktech.plutus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 