server:
  port: 8080

spring:
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5431/plutus
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  
  
  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# Custom Configuration
credit:
  reservation:
    ttl-seconds: 3600  # 1 hour
  rate-limit:
    enabled: true
    window-seconds: 60
    max-requests: 100

