server:
  port: 8080

spring:
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5431/plutus
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: CreditHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
  
  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# Custom Configuration
credit:
  reservation:
    ttl-seconds: 3600  # 1 hour
  rate-limit:
    enabled: true
    window-seconds: 60
    max-requests: 100

# Logging Configuration
logging:
  level:
    root: INFO
    com.looktech.plutus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 