server:
  port: 8080

spring:
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5431/plutus
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

# Custom Configuration
credit:
  reservation:
    ttl-seconds: 3600  # 1 hour
  rate-limit:
    enabled: true
    window-seconds: 60
    max-requests: 100

