apiVersion: v1
kind: ConfigMap
metadata:
  name: plutus-config
data:
  CREDIT_RESERVATION_TTL: '3600'
  DB_NAME: plutus
  DB_HOST: localhost
  DB_PORT: '5432'
  RATE_LIMIT_ENABLED: 'true'
  RATE_LIMIT_MAX_REQUESTS: '100'
  RATE_LIMIT_WINDOW: '60'
  REDIS_DATABASE: '0'
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  REDIS_TIMEOUT: '10000'
  SERVER_PORT: '8080'
  SPRING_PROFILES_ACTIVE: prod
  DB_USERNAME: postgres
  DB_PASSWORD: Look1tech