apiVersion: apps/v1
kind: Deployment
metadata:
  name: plutus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plutus
  template:
    metadata:
      labels:
        app: plutus
    spec:
      containers:
      - name: plutus
        image: plutus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        envFrom:
        - configMapRef:
            name: plutus-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: plutus-config
---
apiVersion: v1
kind: Service
metadata:
  name: plutus
spec:
  selector:
    app: plutus
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 